### ISSUE TITLE
parser.ql, patterndb refactoring

### ISSUE THREAD

**Issue by karolisc** [Security-Onion-Solutions/securityonion-elsa-extras#1]

**Comment by dougburks** [comment]
?

**Comment by karolisc** [comment]
Hi Doug,

I have look at the code today, saw your attempt to structure the code a little bit.
 I thought i could help you with  this. You are grouping files by type in sql and parsers dirs.
Just an idea maybe it would be better to put all the related files (parser, sql) into  "program_name" directory  ? 

Karolis

**Comment by dougburks** [comment]
No, I think it's fine right now.
